//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ichiraku
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int ИдЗаказа { get; set; }
        public Nullable<int> ИдБлюда { get; set; }
        public Nullable<int> ИдОфицианта { get; set; }
        public int КоличествоБлюд { get; set; }
    
        public virtual Блюда Блюда { get; set; }
        public virtual Кассиры Кассиры { get; set; }
    }
}
