//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ichiraku
{
    using System;
    using System.Collections.Generic;
    
    public partial class Чек
    {
        public int ИдЧека { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время { get; set; }
        public double Сумма { get; set; }
        public int ИдЗаказа { get; set; }
        public int НомерЗаказа { get; set; }
        public int ТипОплаты { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual ТипОплаты ТипОплаты1 { get; set; }
    }
}
